PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    ?region a dbo:Country ;
        owl:sameAs ?dbplace .
}
WHERE {
	?region a dbo:Place ;
		rdfs:label ?regionLabel .

	FILTER NOT EXISTS { ?region rdf:type dbo:Continent }
    BIND(REPLACE(?regionLabel, "_", " ") AS ?regionLabelH)
    
    SERVICE <https://dbpedia.org/sparql> {
        ?dbplace a schema:Country ;
                 rdfs:label ?dbplaceLabel .
        FILTER(lang(?dbplaceLabel) = "en")
        FILTER(STR(?regionLabelH) = STR(?dbplaceLabel))
    }
}