BASE <http://cit.tum.de/ressource/travelkg/>
PREFIX mapper: <http://www.ontotext.com/mapper/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX travelkg: <http://cit.tum.de/ontology/travelkg/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX travelregion: <http://cit.tum.de/ressource/travelkg/region/>

CONSTRUCT {

    ?regioniri a rdf:Class ;
        rdfs:label ?c_Region ;
        a dbo:Region ;
        a dbo:Place ;
        dbo:subregion ?parentRegionIRI ;
        travelkg:safetyRating ?safetyRatingIRI ;
        travelkg:timeTo75Utility ?timeTo75UtilityIRI ;
        travelkg:timeTo25Utility ?timeTo25UtilityIRI ;
        travelkg:avgCostPerWeek ?avgCostPerWeekIRI ;
        travelkg:januaryRating ?januaryRatingIRI ;
        travelkg:februaryRating ?februaryRatingIRI ;
        travelkg:marchRating ?marchRatingIRI ;
        travelkg:aprilRating ?aprilRatingIRI ;
        travelkg:mayRating ?mayRatingIRI ;
        travelkg:juneRating ?juneRatingIRI ;
        travelkg:julyating ?julyRatingIRI ;
        travelkg:augustRating ?augustRatingIRI ;
        travelkg:septemberRating ?septemberRatingIRI ;
        travelkg:octoberRating ?octoberRatingIRI ;
        travelkg:novemberRating ?novemberRatingIRI ;
        travelkg:decemberRating ?decemberRatingIRI ;
        
        travelkg:natureWildlifeRating ?natureWildlifeRatingIRI ;
        travelkg:beachRating ?beachRatingIRI ;
        travelkg:waterSportsRating ?waterSportsRatingIRI ;
        travelkg:entertainmentRating ?entertainmentRatingIRI ;
        travelkg:winterSportsRating ?winterSportsRatingIRI ;
        travelkg:cultureRating ?cultureRatingIRI ;
        travelkg:culinaryRating ?culinaryRatingIRI ;
        travelkg:citiesArchitectureRating ?citiesArchitectureRatingIRI .


    ?avgCostPerWeekIRI rdfs:label ?o_AvgCostPerWeek .
    ?safetyRatingIRI rdfs:label ?o_SafetyRating .
    ?timeTo75UtilityIRI rdfs:label ?o_timeTo75Utility .
    ?timeTo25UtilityIRI rdfs:label ?o_timeTo25Utility .

    ?januaryRatingIRI rdfs:label ?o_januaryRating .
    ?februaryRatingIRI rdfs:label ?o_februaryRating .
    ?marchRatingIRI rdfs:label ?o_marchRating .
    ?aprilRatingIRI rdfs:label ?o_aprilRating .
    ?mayRatingIRI rdfs:label ?o_mayRating .
    ?juneRatingIRI rdfs:label ?o_juneRating .
    ?julyRatingIRI rdfs:label ?o_julyRating .
    ?augustRatingIRI rdfs:label ?o_augustRating .
    ?septemberRatingIRI rdfs:label ?o_septemberRating .
    ?decemberRatingIRI rdfs:label ?o_decemberRating .

    travelkg:safetyRating a rdf:Property ;
        rdfs:comment "Safety rating."@en ;
        rdfs:range xsd:nonNegativeInteger ;
    travelkg:timeTo25Utility a rdf:Property ;
        rdfs:comment "Time it takes to reach a utility level of 25 %."@en ;
        rdfs:range xsd:nonNegativeInteger ;
    travelkg:timeTo75Utility a rdf:Property ;
        rdfs:comment "The time it takes to reach a utility level of 75 %."@en ;
        rdfs:range xsd:nonNegativeInteger ;
    travelkg:avgCostPerWeek a rdf:Property ;
        rdfs:comment "Average cost per week."@en ;
        rdfs:range xsd:nonNegativeInteger ;

    travelkg:januaryRating a rdf:Property ;
        rdfs:label "januaryRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:februaryRating a rdf:Property ;
        rdfs:label "februaryRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:marchRating a rdf:Property ;
        rdfs:label "marchRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:aprilRating a rdf:Property ;
        rdfs:label "aprilRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:mayRating a rdf:Property ;
        rdfs:label "mayRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:juneRating a rdf:Property ;
        rdfs:label "juneRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:julyRating a rdf:Property ;
        rdfs:label "julyRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:augustRating a rdf:Property ;
        rdfs:label "augustRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:septemberRating a rdf:Property ;
        rdfs:label "septemberRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:octoberRating a rdf:Property ;
        rdfs:label "octoberRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:novemberRating a rdf:Property ;
        rdfs:label "novemberRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:decemberRating a rdf:Property ;
        rdfs:label "decemberRating" ;
        rdfs:comment "How good it is to visit the region in that month. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .

    travelkg:natureWildlifeRating a rdf:Property ;
        rdfs:label "Nature and wildlife rating" ;
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:beachRating a rdf:Property ;
        rdfs:label "Beach rating" ;
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:waterSportsRating a rdf:Property ;
        rdfs:label "Water sports rating" ;
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:entertainmentRating a rdf:Property ;
        rdfs:label "Entertainment rating";
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:winterSportsRating a rdf:Property ;
        rdfs:label "Winter sports rating";
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:cultureRating a rdf:Property ;
        rdfs:label "Culture rating";
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:culinaryRating a rdf:Property ;
        rdfs:label "Culinary rating";
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .
    travelkg:citiesArchitectureRating a rdf:Property ;
        rdfs:label "Cities and architecture rating";
        rdfs:comment "How well that region is suited for that activity. Rating goes 1 (very poor) - 4 (average) - 7 (excellent)."@en ;
        rdfs:range xsd:nonNegativeInteger .

} WHERE {
    SERVICE <http://localhost:7333/repositories/ontorefine:2455530186488> {
        # Columns as variables:
        #   ?c_Column, ?c_Parent_region, ?c_Region, ?c_SQL_unique_name, ?c_Time_to_75__percentage_daily_utility_in_weeks,
        #   ?c_Time_to_25__percentage_daily_utility_in_weeks, ?c_Avg_cost_per_week,
        #   ?c_January, ?c_February, ?c_March, ?c_April, ?c_May, ?c_June, ?c_July,
        #   ?c_August, ?c_September, ?c_October, ?c_November, ?c_December, ?c_Safety_from_crime,
        #   ?c_Nature_wildlife, ?c_Hiking, ?c_Beach, ?c_Water_sports, ?c_Entertainment,
        #   ?c_Winter_sports, ?c_Culture, ?c_Culinary_arts, ?c_Cities_architecture,
        #   ?c_Shopping
        # Metadata as variables:
        #   ?row_index, ?record_id

        (?row_index "\"safety/\" + cells[\"Safety from crime\"].value") mapper:grel ?o_safetyRating_grel .
        (?row_index "\"timeTo75Utility/\" + cells[\"Time_to_75__percentage_daily_utility_in_weeks\"].value") mapper:grel ?o_timeTo75Utility_grel .
        (?row_index "\"timeTo25Utility/\" + cells[\"Time_to_25__percentage_daily_utility_in_weeks\"].value") mapper:grel ?o_timeTo25Utility_grel .
        (?row_index "\"avgCostPerWeek/\" + cells[\"Avg_cost_per_week\"].value") mapper:grel ?o_avgCostPerWeek_grel .
        (?row_index "\"monthlyRating/january/\" + cells[\"January\"].value") mapper:grel ?o_januaryRating_grel .
        (?row_index "\"monthlyRating/february/\" + cells[\"February\"].value") mapper:grel ?o_februaryRating_grel .
        (?row_index "\"monthlyRating/march/\" + cells[\"March\"].value") mapper:grel ?o_marchRating_grel .
        (?row_index "\"monthlyRating/april/\" + cells[\"April\"].value") mapper:grel ?o_aprilRating_grel .
        (?row_index "\"monthlyRating/may/\" + cells[\"May\"].value") mapper:grel ?o_mayRating_grel .
        (?row_index "\"monthlyRating/june/\" + cells[\"June\"].value") mapper:grel ?o_juneRating_grel .
        (?row_index "\"monthlyRating/july/\" + cells[\"July\"].value") mapper:grel ?o_julyRating_grel .
        (?row_index "\"monthlyRating/august/\" + cells[\"August\"].value") mapper:grel ?o_augustRating_grel .
        (?row_index "\"monthlyRating/september/\" + cells[\"September\"].value") mapper:grel ?o_septemberRating_grel .
        (?row_index "\"monthlyRating/october/\" + cells[\"October\"].value") mapper:grel ?o_octoberRating_grel .
        (?row_index "\"monthlyRating/november/\" + cells[\"November\"].value") mapper:grel ?o_novemberRating_grel .
        (?row_index "\"monthlyRating/december/\" + cells[\"December\"].value") mapper:grel ?o_decemberRating_grel .

        (?row_index "\"activityRating/nature_wildlife/\" + cells[\"Nature_wildlife\"].value") mapper:grel ?o_natureWildlifeRating_grel .
        (?row_index "\"activityRating/hiking/\" + cells[\"Hiking\"].value") mapper:grel ?o_hikingRating_grel .
        (?row_index "\"activityRating/beach/\" + cells[\"Beach\"].value") mapper:grel ?o_beachRating_grel .
        (?row_index "\"activityRating/water_sports/\" + cells[\"Water_sports\"].value") mapper:grel ?o_waterSportsRating_grel .
        (?row_index "\"activityRating/entertainment/\" + cells[\"Entertainment\"].value") mapper:grel ?o_entertainmentRating_grel .
        (?row_index "\"activityRating/winter_sports/\" + cells[\"Winter_sports\"].value") mapper:grel ?o_winterSportsRating_grel .
        (?row_index "\"activityRating/culture/\" + cells[\"Culture\"].value") mapper:grel ?o_cultureRating_grel .
        (?row_index "\"activityRating/culinary/\" + cells[\"Culinary_arts\"].value") mapper:grel ?o_culinaryRating_grel .
        (?row_index "\"activityRating/cities_architecture/\" + cells[\"Cities_architecture\"].value") mapper:grel ?o_citiesArchitectureRating_grel .
        (?row_index "\"activityRating/shopping/\" + cells[\"Shopping\"].value") mapper:grel ?o_shoppingRating_grel .

        BIND(STRDT(?c_Avg_cost_per_week, xsd:nonNegativeInteger) as ?o_AvgCostPerWeek)
        BIND(STRDT(?c_Safety_from_crime, xsd:nonNegativeInteger) as ?o_SafetyRating)
        BIND(STRDT(?c_Time_to_75__percentage_daily_utility_in_weeks, xsd:positiveInteger) as ?o_timeTo75Utility)
        BIND(STRDT(?c_Time_to_25__percentage_daily_utility_in_weeks, xsd:positiveInteger) as ?o_timeTo25Utility)
        BIND(STRDT(?c_January, xsd:nonNegativeInteger) as ?o_januaryRating)
        BIND(STRDT(?c_February, xsd:nonNegativeInteger) as ?o_februaryRating)
        BIND(STRDT(?c_March, xsd:nonNegativeInteger) as ?o_marchRating)
        BIND(STRDT(?c_April, xsd:nonNegativeInteger) as ?o_aprilRating)
        BIND(STRDT(?c_May, xsd:nonNegativeInteger) as ?o_mayRating)
        BIND(STRDT(?c_June, xsd:nonNegativeInteger) as ?o_juneRating)
        BIND(STRDT(?c_July, xsd:nonNegativeInteger) as ?o_julyRating)
        BIND(STRDT(?c_August, xsd:nonNegativeInteger) as ?o_augustRating)
        BIND(STRDT(?c_September, xsd:nonNegativeInteger) as ?o_septemberRating)
        BIND(STRDT(?c_October, xsd:nonNegativeInteger) as ?o_octoberRating)
        BIND(STRDT(?c_November, xsd:nonNegativeInteger) as ?o_novemberRating)
        BIND(STRDT(?c_December, xsd:nonNegativeInteger) as ?o_decemberRating)
        BIND(STRDT(?c_Nature_wildlife, xsd:nonNegativeInteger) as ?o_natureWildlifeRating)
        BIND(STRDT(?c_Hiking, xsd:nonNegativeInteger) as ?o_hikingRating)
        BIND(STRDT(?c_Beach, xsd:nonNegativeInteger) as ?o_beachRating)
        BIND(STRDT(?c_Water_sports, xsd:nonNegativeInteger) as ?o_waterSportsRating)
        BIND(STRDT(?c_Entertainment, xsd:nonNegativeInteger) as ?o_entertainmentRating)
        BIND(STRDT(?c_Winter_sports, xsd:nonNegativeInteger) as ?o_winterSportsRating)
        BIND(STRDT(?c_Culture, xsd:nonNegativeInteger) as ?o_cultureRating)
        BIND(STRDT(?c_Culinary_arts, xsd:nonNegativeInteger) as ?o_culinaryRating)
        BIND(STRDT(?c_Cities_architecture, xsd:nonNegativeInteger) as ?o_citiesArchitectureRating)
        BIND(STRDT(?c_Shopping, xsd:nonNegativeInteger) as ?o_shoppingRating)

        # IRI mappings
        BIND(IRI(mapper:encode_iri(travelregion:, ?c_Region)) as ?regioniri)
        BIND(IRI(mapper:encode_iri(travelregion:, ?c_Parent_region)) as ?parentRegionIRI)
        BIND(IRI(mapper:encode_iri(?o_avgCostPerWeek_grel)) as ?avgCostPerWeekIRI)
        BIND(IRI(mapper:encode_iri(?o_safetyRating_grel)) as ?safetyRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_timeTo75Utility_grel)) as ?timeTo75UtilityIRI)
        BIND(IRI(mapper:encode_iri(?o_timeTo25Utility_grel)) as ?timeTo25UtilityIRI)

        # Monthly ratings
        BIND(IRI(mapper:encode_iri(?o_januaryRating_grel)) as ?januaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_februaryRating_grel)) as ?februaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_marchRating_grel)) as ?marchRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_aprilRating_grel)) as ?aprilRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_mayRating_grel)) as ?mayRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_juneRating_grel)) as ?juneRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_julyRating_grel)) as ?julyRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_augustRating_grel)) as ?augustRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_septemberRating_grel)) as ?septemberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_octoberRating_grel)) as ?octoberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_novemberRating_grel)) as ?novemberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_decemberRating_grel)) as ?decemberRatingIRI)

        # Activity ratings
        BIND(IRI(mapper:encode_iri(?o_natureWildlifeRating_grel)) as ?natureWildlifeRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_hikingRating_grel)) as ?hikingRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_beachRating_grel)) as ?beachRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_waterSportsRating_grel)) as ?waterSportsRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_entertainmentRating_grel)) as ?entertainmentRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_winterSportsRating_grel)) as ?winterSportsRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_cultureRating_grel)) as ?cultureRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_culinaryRating_grel)) as ?culinaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_citiesArchitectureRating_grel)) as ?citiesArchitectureRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_shoppingRating_grel)) as ?shoppingRatingIRI)
    }
}