BASE <http://cit.tum.de/ressource/travelkg/>
PREFIX mapper: <http://www.ontotext.com/mapper/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX travelkg: <http://cit.tum.de/ontology/travelkg/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX travelregion: <http://cit.tum.de/ressource/travelkg/region/>
PREFIX schema: <http://schema.org/>

CONSTRUCT {

    ?regionIRI rdfs:label ?c_Region ;
        a dbo:Place ;
        a dbo:PopulatedPlace ;
        a schema:Place .

    ?regionIRI dbo:subregion ?parentRegionIRI ;
        travelkg:safetyRating ?o_SafetyRating ;
        travelkg:timeTo75Utility ?o_timeTo75Utility ;
        travelkg:timeTo25Utility ?o_timeTo25Utility ;
        travelkg:avgCostPerWeek ?o_AvgCostPerWeek ;

        travelkg:januaryRating ?januaryRatingIRI ;
        travelkg:februaryRating ?februaryRatingIRI ;
        travelkg:marchRating ?marchRatingIRI ;
        travelkg:aprilRating ?aprilRatingIRI ;
        travelkg:mayRating ?mayRatingIRI ;
        travelkg:juneRating ?juneRatingIRI ;
        travelkg:julyRating ?julyRatingIRI ;
        travelkg:augustRating ?augustRatingIRI ;
        travelkg:septemberRating ?septemberRatingIRI ;
        travelkg:octoberRating ?octoberRatingIRI ;
        travelkg:novemberRating ?novemberRatingIRI ;
        travelkg:decemberRating ?decemberRatingIRI ;
        
        travelkg:natureRating ?natureWildlifeRatingIRI ;
        travelkg:hikingRating ?hikingRatingIRI ;
        travelkg:beachRating ?beachRatingIRI ;
        travelkg:waterSportsRating ?waterSportsRatingIRI ;
        travelkg:entertainmentRating ?entertainmentRatingIRI ;
        travelkg:winterSportsRating ?winterSportsRatingIRI ;
        travelkg:cultureRating ?cultureRatingIRI ;
        travelkg:culinaryRating ?culinaryRatingIRI ;
        travelkg:citiesArchitectureRating ?citiesArchitectureRatingIRI ;
        travelkg:shoppingRating ?shoppingRatingIRI .

    # assign labels as string or number
    ?januaryRatingIRI rdfs:label ?o_January .
    ?februaryRatingIRI rdfs:label ?o_February .
    ?marchRatingIRI rdfs:label ?o_March .
    ?aprilRatingIRI rdfs:label ?o_April .
    ?mayRatingIRI rdfs:label ?o_May .
    ?juneRatingIRI rdfs:label ?o_June .
    ?julyRatingIRI rdfs:label ?o_July .
    ?augustRatingIRI rdfs:label ?o_August .
    ?septemberRatingIRI rdfs:label ?o_September .
    ?decemberRatingIRI rdfs:label ?o_December .
    # label the resources
    ?natureWildlifeRatingIRI rdfs:label ?o_Nature_wildlife .
    ?hikingRatingIRI rdfs:label ?o_Hiking .
    ?beachRatingIRI rdfs:label ?o_Beach .
    ?waterSportsRatingIRI rdfs:label ?o_Water_sports.
    ?entertainmentRatingIRI rdfs:label ?o_Entertainment .
    ?winterSportsRatingIRI rdfs:label ?o_Winter_sports .
    ?cultureRatingIRI rdfs:label ?o_Culture .
    ?culinaryRatingIRI rdfs:label ?o_Culinary_arts .
    ?citiesArchitectureRatingIRI rdfs:label ?o_Cities_architecture .
    ?shoppingRatingIRI rdfs:label ?o_Shopping .

    travelkg:LikertRating rdfs:subClassOf schema:Rating ;
        schema:worstRating 1 ;
        schema:bestRating 5 .

    travelkg:monthlyRating a rdf:Property ;
        a schema:ratingValue ;
        rdfs:comment "Rating on how good it is to visit for a specific month (1-5)."@en ;
        rdfs:range travelkg:LikertRating .

    travelkg:safetyRating a rdf:Property ;
        a schema:ratingValue ;
        rdfs:comment"Safety from crime."@en ;
        rdfs:range travelkg:LikertRating .

    travelkg:timeTo25Utility a rdf:Property ;
        rdfs:comment "Time in weeks it takes to reach a utility level of 25 %."@en ;
        rdfs:range xsd:nonNegativeInteger .

    travelkg:timeTo75Utility a rdf:Property ;
        rdfs:comment "Time in weeks it takes to reach a utility level of 75 %."@en ;
        rdfs:range xsd:nonNegativeInteger .

    travelkg:avgCostPerWeek a rdf:Property ;
        rdfs:comment "Average cost per week."@en ;
        rdfs:range xsd:nonNegativeInteger .

    travelkg:januaryRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:februaryRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:marchRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:aprilRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:mayRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:juneRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:julyRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:augustRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:septemberRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:octoberRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:novemberRating rdfs:subPropertyOf travelkg:monthlyRating .
    travelkg:decemberRating rdfs:subPropertyOf travelkg:monthlyRating .

    travelkg:natureRating a rdf:Property ;
        rdfs:comment "How well it is suited for nature and wildlife."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:hikingRating a rdf:Property ;
        rdfs:comment "How well it is suited for hiking."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:beachRating a rdf:Property ;
        rdfs:comment "How well it is suited for beach."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:waterSportsRating a rdf:Property ;
        rdfs:comment  "How well it is suited for water sports."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:winterSportsRating a rdf:Property ;
        rdfs:comment  "How well it is suited for winter sports."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:cultureRating a rdf:Property ;
        rdfs:comment  "How well it is suited for culture."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:culinaryRating a rdf:Property ;
        rdfs:comment  "How well it is suited for culinary."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:citiesArchitectureRating a rdf:Property ;
        rdfs:comment  "How well it is suited for cities and architecture."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:entertainmentRating a rdf:Property ;
        rdfs:comment  "How well it is suited for entertainment."@en ;
        rdfs:range travelkg:LikertRating .
    travelkg:shoppingRating a rdf:Property ;
        rdfs:comment  "How well it is suited for shopping."@en ;
        rdfs:range travelkg:LikertRating .

} WHERE {
    SERVICE <http://localhost:7333/repositories/ontorefine:2146414991628> {
        # Columns as variables:
        #   ?c_Column, ?c_Parent_region, ?c_Region, ?c_SQL_unique_name, ?c_Time_to_75__percentage_daily_utility_in_weeks,
        #   ?c_Time_to_25__percentage_daily_utility_in_weeks, ?c_Avg_cost_per_week,
        #   ?c_January, ?c_February, ?c_March, ?c_April, ?c_May, ?c_June, ?c_July,
        #   ?c_August, ?c_September, ?c_October, ?c_November, ?c_December, ?c_Safety_from_crime,
        #   ?c_Nature_wildlife, ?c_Hiking, ?c_Beach, ?c_Water_sports, ?c_Entertainment,
        #   ?c_Winter_sports, ?c_Culture, ?c_Culinary_arts, ?c_Cities_architecture,
        #   ?c_Shopping
        # Metadata as variables:
        #   ?row_index, ?record_id

        (?row_index "\"monthlyRating/january/\" + cells[\"January\"].value") mapper:grel ?o_januaryRating_grel .
        (?row_index "\"monthlyRating/february/\" + cells[\"February\"].value") mapper:grel ?o_februaryRating_grel .
        (?row_index "\"monthlyRating/march/\" + cells[\"March\"].value") mapper:grel ?o_marchRating_grel .
        (?row_index "\"monthlyRating/april/\" + cells[\"April\"].value") mapper:grel ?o_aprilRating_grel .
        (?row_index "\"monthlyRating/may/\" + cells[\"May\"].value") mapper:grel ?o_mayRating_grel .
        (?row_index "\"monthlyRating/june/\" + cells[\"June\"].value") mapper:grel ?o_juneRating_grel .
        (?row_index "\"monthlyRating/july/\" + cells[\"July\"].value") mapper:grel ?o_julyRating_grel .
        (?row_index "\"monthlyRating/august/\" + cells[\"August\"].value") mapper:grel ?o_augustRating_grel .
        (?row_index "\"monthlyRating/september/\" + cells[\"September\"].value") mapper:grel ?o_septemberRating_grel .
        (?row_index "\"monthlyRating/october/\" + cells[\"October\"].value") mapper:grel ?o_octoberRating_grel .
        (?row_index "\"monthlyRating/november/\" + cells[\"November\"].value") mapper:grel ?o_novemberRating_grel .
        (?row_index "\"monthlyRating/december/\" + cells[\"December\"].value") mapper:grel ?o_decemberRating_grel .

        (?row_index "\"activityRating/nature_wildlife/\" + cells[\"Nature_wildlife\"].value") mapper:grel ?o_natureWildlifeRating_grel .
        (?row_index "\"activityRating/hiking/\" + cells[\"Hiking\"].value") mapper:grel ?o_hikingRating_grel .
        (?row_index "\"activityRating/beach/\" + cells[\"Beach\"].value") mapper:grel ?o_beachRating_grel .
        (?row_index "\"activityRating/water_sports/\" + cells[\"Water_sports\"].value") mapper:grel ?o_waterSportsRating_grel .
        (?row_index "\"activityRating/entertainment/\" + cells[\"Entertainment\"].value") mapper:grel ?o_entertainmentRating_grel .
        (?row_index "\"activityRating/winter_sports/\" + cells[\"Winter_sports\"].value") mapper:grel ?o_winterSportsRating_grel .
        (?row_index "\"activityRating/culture/\" + cells[\"Culture\"].value") mapper:grel ?o_cultureRating_grel .
        (?row_index "\"activityRating/culinary/\" + cells[\"Culinary_arts\"].value") mapper:grel ?o_culinaryRating_grel .
        (?row_index "\"activityRating/cities_architecture/\" + cells[\"Cities_architecture\"].value") mapper:grel ?o_citiesArchitectureRating_grel .
        (?row_index "\"activityRating/shopping/\" + cells[\"Shopping\"].value") mapper:grel ?o_shoppingRating_grel .

        BIND(STRDT(?c_Avg_cost_per_week, xsd:nonNegativeInteger) as ?o_AvgCostPerWeek)
        BIND(STRDT(?c_Safety_from_crime, xsd:nonNegativeInteger) as ?o_SafetyRating)
        BIND(STRDT(?c_Time_to_75__percentage_daily_utility_in_weeks, xsd:nonNegativeInteger) as ?o_timeTo75Utility)
        BIND(STRDT(?c_Time_to_25__percentage_daily_utility_in_weeks, xsd:nonNegativeInteger) as ?o_timeTo25Utility)
        BIND(STRDT(?c_January, xsd:nonNegativeInteger) as ?o_January)
        BIND(STRDT(?c_February, xsd:nonNegativeInteger) as ?o_February)
        BIND(STRDT(?c_March, xsd:nonNegativeInteger) as ?o_March)
        BIND(STRDT(?c_April, xsd:nonNegativeInteger) as ?o_April)
        BIND(STRDT(?c_May, xsd:nonNegativeInteger) as ?o_May)
        BIND(STRDT(?c_June, xsd:nonNegativeInteger) as ?o_June)
        BIND(STRDT(?c_July, xsd:nonNegativeInteger) as ?o_July)
        BIND(STRDT(?c_August, xsd:nonNegativeInteger) as ?o_August)
        BIND(STRDT(?c_September, xsd:nonNegativeInteger) as ?o_September)
        BIND(STRDT(?c_October, xsd:nonNegativeInteger) as ?o_October)
        BIND(STRDT(?c_November, xsd:nonNegativeInteger) as ?o_November)
        BIND(STRDT(?c_December, xsd:nonNegativeInteger) as ?o_December)
        BIND(STRDT(?c_Nature_wildlife, xsd:nonNegativeInteger) as ?o_Nature_wildlife)
        BIND(STRDT(?c_Hiking, xsd:nonNegativeInteger) as ?o_Hiking)
        BIND(STRDT(?c_Beach, xsd:nonNegativeInteger) as ?o_Beach)
        BIND(STRDT(?c_Water_sports, xsd:nonNegativeInteger) as ?o_Water_sports)
        BIND(STRDT(?c_Entertainment, xsd:nonNegativeInteger) as ?o_Entertainment)
        BIND(STRDT(?c_Winter_sports, xsd:nonNegativeInteger) as ?o_Winter_sports)
        BIND(STRDT(?c_Culture, xsd:nonNegativeInteger) as ?o_Culture)
        BIND(STRDT(?c_Culinary_arts, xsd:nonNegativeInteger) as ?o_Culinary_arts)
        BIND(STRDT(?c_Cities_architecture, xsd:nonNegativeInteger) as ?o_Cities_architecture)
        BIND(STRDT(?c_Shopping, xsd:nonNegativeInteger) as ?o_Shopping)

        ## IRI mappings
        BIND(IRI(mapper:encode_iri(travelregion:, ?c_Region)) as ?regionIRI)
        BIND(IRI(mapper:encode_iri(travelregion:, ?c_Parent_region)) as ?parentRegionIRI)

        ## Monthly ratings
        BIND(IRI(mapper:encode_iri(?o_januaryRating_grel)) as ?januaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_februaryRating_grel)) as ?februaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_marchRating_grel)) as ?marchRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_aprilRating_grel)) as ?aprilRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_mayRating_grel)) as ?mayRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_juneRating_grel)) as ?juneRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_julyRating_grel)) as ?julyRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_augustRating_grel)) as ?augustRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_septemberRating_grel)) as ?septemberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_octoberRating_grel)) as ?octoberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_novemberRating_grel)) as ?novemberRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_decemberRating_grel)) as ?decemberRatingIRI)

        ## Activity ratings
        BIND(IRI(mapper:encode_iri(?o_natureWildlifeRating_grel)) as ?natureWildlifeRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_hikingRating_grel)) as ?hikingRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_beachRating_grel)) as ?beachRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_waterSportsRating_grel)) as ?waterSportsRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_entertainmentRating_grel)) as ?entertainmentRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_winterSportsRating_grel)) as ?winterSportsRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_cultureRating_grel)) as ?cultureRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_culinaryRating_grel)) as ?culinaryRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_citiesArchitectureRating_grel)) as ?citiesArchitectureRatingIRI)
        BIND(IRI(mapper:encode_iri(?o_shoppingRating_grel)) as ?shoppingRatingIRI)
    }
}