# coding: utf-8

"""
    RDF4J API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contexts_api import ContextsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContextsApi(unittest.TestCase):
    """ContextsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.contexts_api.ContextsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_repository_contexts(self):
        """Test case for get_repository_contexts

        Gets a list of resources that are used as context identifiers.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
